### ISSUE TITLE
This project is very good. Where did you get the data source?

### ISSUE THREAD

**Issue by yxj1028530975** [yetanothercheer/Archive#1]
Such as title.

**Comment by yetanothercheer** [comment]
Currently, api endpoints are found from https://m.weibo.cn/, also authentication is not required, so HTTP GET would suffice.

**Comment by yxj1028530975** [comment]
能分享api接口吗，或者是程序

**Comment by yetanothercheer** [comment]
Sure! I happend to be rewriting the code , just created a [public repo](https://github.com/yetanothercheer/CodeForArchive). [crawler.py](https://github.com/yetanothercheer/CodeForArchive/blob/main/crawler.py) contains api, it was pasted from browser devtool.

**Comment by yxj1028530975** [comment]
Thanks a lot,this helped me a lot.

**Comment by yetanothercheer** [comment]
🙆‍♂️
